apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: $vip
    k8sServicePort: 6443
    k8sClientRateLimit:
      qps: 33
      burst: 40
    l2announcements:
      enabled: true
      leaseDuration: "3s"
      leaseRenewDeadline: "1s"
      leaseRetryPeriod: "200ms"
    externalIPs:
      enabled: true
    operator:
      replicas: 2
    ipam:
      mode: cluster-pool
      clusterPoolIPv4PodCIDRList:
        - "10.42.0.0/16"
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    envoy:
      enabled: false
