apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: $vip
    k8sServicePort: 6443
    prometheus:
      enabled: true
    operator:
      replicas: 2
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
    ipam:
      mode: cluster-pool
      clusterPoolIPv4PodCIDRList:
        - "10.42.0.0/16"
      enable-external-ips: false
    hubble:
      enabled: true
      relay:
        enabled: true
        prometheus:
          enabled: true
      ui:
        enabled: true
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - icmp
          - http
        dashboards:
          enabled: true
    envoy:
      enabled: false
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
